.TH crimesquad 6 2007-06-16
.SH NAME
crimesquad - Liberal Crime Squad
.SH DESCRIPTION
.P
A satirical console-based political role-playing/strategy game in which you recruit 
a team of Elite Liberal radicals and try to save the United States from a descent 
into Arch-Conservatism. Gameplay based loosely on the classic 1983 RPG Oubliette.
.P
See the manual for gameplay information. The manual should have been included in the
docs folder of your download, but it is also available online.
.SH AVAILABILITY
All UNIX flavors as well as all Win32.
.SH REQUIRES
ncurses (or pdcurses on Win32)
.SH AUTHORS
Tarn Adams - Created original game. 
.br
Kevin Sadler - Created Linux port and fixed bugs. 
.P
Current Developers: 
.P
Jonathan Stickles (jonathansfox@users.sourceforge.net)
.br
Chris Johnson (grundee@users.sourceforge.net)

